name: Architectural Alchemy
favicon: null
layout_spectrum: 0.25916
typography_spectrum: 0.06994
title: Architectural Alchemy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#de0907'
    - '#02abea'
    - '#7f7f7f'
    - '#fbf305'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
