name: Architectural Alchemy
favicon: null
layout_spectrum: 0.38531909231096506
typography_spectrum: 0.9624206507578492
title: Positive Global Change through Architecture and Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3642788559664041
  lightness: 0.6301762568764389
  saturation: 0.2478540309239179
  rhythmicContrast: 0.1115482912864536
purpose: []
