name: Architectural Alchemy
favicon: null
layout_spectrum: 0.22883
typography_spectrum: 0.22198
title: Positive Global Change through Architecture and Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
